apiVersion: apps/v1
kind: Deployment
metadata:
  name: brahmaputra-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brahmaputra-agent
  template:
    metadata:
      labels:
        app: brahmaputra-agent
    spec:
      containers:
      - name: brahmaputra-agent
        image: myfirstaksdemoacr.azurecr.io/brahmaputra-agent-ada:#{Build.BuildId}#
        ports:
          - containerPort: 8000
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
    name: brahmaputra-agent
spec:
  selector:
    app: brahmaputra-agent # Change the selector to a non-existent pod label
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer